config/routes.rb
Rails.application.routes.draw do
  root 'access#home_page', as: 'home_page'
  get 'access/home_page'

  post '/access/login', to: "access#attempt_login", as: 'login'
  delete '/logout', to: 'access#logout', as: 'logout'

  get 'access/about'

  resources :users do
    resources :pets
  end

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  belongs_to :users, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pets
  has_secure_password

  validates :first_name, presence: true, length: { minimum: 3 }
  validates :last_name, presence: true, length: { minimum: 2 }

  validates :email, presence: true, uniqueness: true
  validates :password, length: { in: 6..20, too_long: "20 characters is 
  the maximum allowed", too_short: "6 characters is the minimum allowed" }

#   validates :vet_name, presence: true
#   validates :vet_number, presence: true, format: { with: /(?:(?:\+?1\s*
#     (?:[.-]\s*)?)?(?:(\s*([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]‌​)\s*)
#     |([2-9]1[02-9]|[2-9][02-8]1|[2-9][02-8][02-9]))\s*(?:[.-]\s*)?)
#     ([2-9]1[02-9]‌​|[2-9][02-9]1|[2-9][02-9]{2})\s*(?:[.-]\s*)?([0-9]{4})/,
#     message: "only allows numbers" }

#   validates :vet_address, presence: true



end

app/controllers/access_controller.rb
class AccessController < ApplicationController

  def home_page
  end

  def about
  end

  def tips
  end

  def attempt_login
    if params[:email].present? && params[:password].present?
      found_user = User.where(email: params[:email]).first
      if found_user
        authorized_user = found_user.authenticate(params[:password])
        if authorized_user
          session[:user_id] = found_user.id
          # redirect_to "/users/#{found_user.id.to_s}", notice: "You are logged in"
          redirect_to user_path authorized_user, notice: "You are logged in"
        else
          redirect_to :back, notice: "Incorrect email or password"
        end
      else
        redirect_to :back, notice: "Incorrect email or password"
      end
    else
      redirect_to :back, notice: "Please enter email and password."
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "You have logged out"
    redirect_to "/"
  end

  private 

  def user_params
    params.require(:user).permit(:email, :password, :password_digest)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  
  def index
    @user = User.find(params[:user_id])
    @pets = @user.pets
  end

  def new
    @user = User.find(params[:user_id])
    @pet = Pet.new
  end

  def create
    @user = User.find_by_id(params[:user_id])
    @pet = Pet.new pet_params 
    @user.pets << @pet
    @pet.user_id = @user.id
    @pet.save
    redirect_to user_pet_path @user.id, @pet.id
  end

  def show
    @user = User.find(params[:user_id])
    @pet = Pet.find(params[:id])
  end

  def edit
    @user = User.find(params[:user_id])
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    @pet.update_attributes pet_params
    redirect_to user_pet_path
  end

  def destroy
    @user = User.find(params[:user_id])
    Pet.destroy (params[:id])
    flash[:notice] = "You have deleted your pet's profile."
    redirect_to user_path(@user)
  end

  private
  def pet_params
    params.require(:pet).permit(:id, :name, :pet_type, :breed, 
      :birthday, :gender, :altered, :weight, :color, :microchip_company, 
      :microchip_company_website, :microchip_company_phone, 
      :microchip_registration_number, :county_registration_number, 
      :county_registration_contact, :county_registration_expiration, 
      :rabies_vaccination_number, :rabies_expiration, :care_instructions, 
      :special_needs, :historical_information, :photo, :vet_records)


  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :prevent_login_signup, only: [:new, :create]
  # before_action only: :edit do
  #   invalid_edit params[:id]
  # end
    
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    #@user.update(profile_pic: params[:uploadcare])

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path @user, notice: "Success, your profile was created."
    else
      flash.now[:alert] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @pets = @user.pets
  end

  def edit
    @user = User.find(params[:id])
    @pets = @user.pets
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes user_params
    redirect_to user_path(@user)
  end

  def destroy
    User.destroy(session[:user_id])
    session[:user_id] = nil
    flash[:notice] = "You deleted your account."
    redirect_to access_home_page_path
  end

  private
  def user_params
    params.require(:user).permit(:id, :first_name, :last_name, :email, :password, :password_digest, :photo, :vet_name, :vet_number, :vet_address)
  end
end

app/helpers/access_helper.rb
module AccessHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/access/about.html.erb
<div class="center">
  <h1>About <span class="whskr">whskr</span></h1>
  <br>
  <h4>
    <span class="whskr">whskr</span> is the best place to store historical records for your pets. 
    <br><br>
    Convenient and easy to use, <span class="whskr">whskr</span> allows users to track vet appointments, medical procedures and any health-relevant information for each pet. Users can also store up to 15 files per pet.
    <br><br>
    <span class="whskr">whskr</span> was made in 9 days (many of them with a cat or cats on my lap) during General Assembly WDI-16 using Ruby on Rails, Javascript, JQuery, Bootstrap, Font Awesome, Google Fonts, UploadCare and HTML/CSS. 
  </h4>
</div>

app/views/access/home_page.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-7">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="4500">

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
        
          <div class="item active">
            <img src="http://c3.staticflickr.com/3/2940/13930649657_84f81018a6_n.jpg" alt="">
          </div>

          <div class="item">
            <img src="http://www.rgbstock.com/cache1qYRF7/users/a/al/alexfryatt/300/n9bHwrC.jpg" alt="">
          </div>

          <div class="item">
            <img src="http://c4.staticflickr.com/4/3825/8835491355_62a2d08db3_n.jpg" alt="">
          </div>
        
          <div class="item">
            <img src="http://c4.staticflickr.com/4/3885/14519742415_002a60fd94_n.jpg" alt="">
          </div>      
        </div> <!-- end class="carousel-inner container" -->
      </div> <!-- end id="carousel-example-generic" -->
    </div> <!-- end class="col-sm-7" -->

    <div class="col-sm-5 home-right">
      <br><br><br><br>
      <p id="Calligraffitti">whskr</p>
      <h2>Manage appointments and records for your pets</h2>
    </div> <!-- end class="col-sm-5 home-right" -->

  </div> <!-- end class="row" -->
</div> <!-- end class="container" -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project3</title>
  <!-- JQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
  <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- end bootstrap -->
  <!-- Font Awesome -->
    <!-- requires bootstrap -->
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <!-- end fontawesome -->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- google fonts -->
  <link href='//fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Arimo|Calligraffitti' rel='stylesheet' type='text/css'>
  <!-- end -->

  <!-- Widget config for Upload Care -->
  <script>
    UPLOADCARE_PUBLIC_KEY = "35f5e08144945413dce9";
  </script>
  <script charset="utf-8" src="https://ucarecdn.com/widget/2.0.6/uploadcare/uploadcare.full.min.js"></script>
  <!-- end -->

</head>
<body>
<!-- nav bar -->
  <nav class="navbar navbar-default">
    <div class="container-fluid" class="navcontainer">
      <a href="/">
      <p class="navbar-text navbar-left"><span>whskr</span></p>
      </a>
      <ul class="nav navbar-nav navbar-right">
        <% if !session[:user_id] %>
          <li>
            <%= form_tag(login_path, class: 'navbar-form navbar-left extra-padding-to-nav') do %>
              <%= label_tag(:email) %>
              <%= text_field_tag(:email, params[:email]) %>

              <%= label_tag(:password) %>
              <%= password_field_tag(:password, params[:password]) %>

              <%= submit_tag("Login") %>
            <% end %>
          </li>
        <% end %>
       

        <li><%= link_to("About", controller: "access", action: "about") %></li>
        <% if session[:user_id] %>
            <li><%= link_to("Profile", "/users/#{session[:user_id]}") %></li>
            <li><%= link_to "Edit Profile", "/users/#{session[:user_id]}/edit"%></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li> 
          
          
        <% else %>
          <li><%= link_to("Sign Up", "/users/new") %></li>
        <% end %>
      </ul>
    </div>
  </nav>
<!-- end nav bar -->

<!-- allow flash messages -->
  <% flash.each do |key, value| %>
  
    <% if key == "notice" %>
      <%= content_tag :div, value, class: "text-center alert alert-warning flashMessage" %>
    <% elsif key == "alert" %>
      <%= content_tag :div, value, class: "text-center alert alert-danger flashMessage" %>
    <% else %>
      <%= content_tag :div, value, class: "text-center alert alert-success flashMessage" %>
    <% end %>
  <% end %>
<!-- end flash messages -->

<%= yield %>

</body>
</html>

app/views/pets/edit.html.erb
<h1>Edit <%= @pet.name %>'s Profile</h1>
<div class="center">
  <%= form_for @pet, url:user_pet_path do |f| %>
    <div class="profile_photo" style="background-image: url(<%= @pet.photo %>); margin: 0 auto;"></div>
    <br>

    <p><b> Change Profile Picture For <%= @pet.name %></b></p>
    <input type="hidden" role="uploadcare-uploader" data-multiple="false" name="pet[photo]" value="<%= @pet.photo %>"/>
    <br><br>

    <p>
      <%= f.label :name%>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :pet_type, required: true%>
      <%= f.select(:pet_type, [["Cat", "Cat"],["Dog", "Dog"],["Horse", "Horse"],
      ["Small Mammal", "Small Mammal"], ["Reptile/Amphibian", "Reptile/Amphibian"], ["Bird", "Bird"], ["Fish/Aquatic", "Fish/Aquatic"], ["Other", "Other"]]) %>
    </p> 
    <p>
      <%= f.label :breed%>
      <%= f.text_field :breed %>
    </p>
    <p>
      <%= f.label :birthday%>
      <%= f.date_field :birthday %>
    </p>
    <p>
      <%= f.radio_button :gender, "female" %>
        <%= f.label :gender, "Female", :value => "female" %>
        <%= f.radio_button :gender, "male" %>
        <%= f.label :gender, "Male", :value => "male" %>
        <br>
        <%= f.radio_button :altered, "altered" %>
        <%= f.label :altered, "Altered", :value => "altered" %>
        <%= f.radio_button :altered, "unaltered" %>
        <%= f.label :altered, "Unaltered", :value => "unaltered" %>
    </p>
    <p>
      <%= f.label :weight%>
      <%= f.text_field :weight %>
    </p>
      <p>
      <%= f.label :color%>
      <%= f.text_field :color %>
    </p>
    <br>
    <p>
      <%= f.label :microchip_number%>
      <%= f.text_field :microchip_number %>
    <br>
    <p>
      <%= f.label :microchip_company%>
      <%= f.text_field :microchip_company %>
    <br>
      <%= f.label :microchip_company_website%>
      <%= f.url_field :microchip_company_website %>
    <br>
      <%= f.label :microchip_company_phone%>
      <%= f.telephone_field :microchip_company_phone %>
    <br>
      <%= f.label :microchip_registration_number%>
      <%= f.text_field :microchip_registration_number %>
    </p>
    <br>
    <p>
      <%= f.label :county_registration_number%>
      <%= f.text_field :county_registration_number %>
    <br>
      <%= f.label :county_registration_contact%>
      <%= f.text_field :county_registration_contact %>
    <br>
      <%= f.label :county_registration_expiration%>
      <%= f.date_field :county_registration_expiration %>
    </p>
    <br>
    <p>
      <%= f.label :rabies_vaccination_number%>
      <%= f.text_field :rabies_vaccination_number %>
    <br>
      <%= f.label :rabies_expiration%>
      <%= f.text_field :rabies_expiration %>
    </p>
    <br>
    <p>
      <%= f.label :care_instructions%>
      <br>
      <%= f.text_area :care_instructions, rows: 10, cols: 80 %>
    </p>
    <br>
    <p>
      <%= f.label :special_needs%>
      <br>
      <%= f.text_area :special_needs, rows: 10, cols: 80 %>
    </p> 
    <br> 
    <p>
      <%= f.label :historical_information%>
      <br>
      <%= f.text_area :historical_information, rows: 10, cols: 80 %>
    </p>  
  <br><br><br>

    <% if @pet.vet_records.present? == true %>
      <% @pet.vet_records.split("~")[1].split("/")[0].to_i.times do |i| %>
        <a class="record_picture" href="<%= "#{@pet.vet_records}nth/#{i}/" %>" alt=""> <i class="icon-file"></i> Record <%= i+1 %>   </a>
      <% end %>
    <% end %>
    <br><br>

    <p><b> Edit Records For <%= @pet.name %></b></p> 
    <input
      type="hidden"
      role="uploadcare-uploader"
      data-images-only="false"
      data-multiple="true"
      name="pet[vet_records]"
      value="<%= @pet.vet_records %>"
      data-multiple-max="15"
    />
    <br><br>

    <%= f.submit "save" %>
  <% end %> <!-- end form -->
</div>

app/views/pets/new.html.erb
<h1>Create a New Pet</h1>
  <div class="center">
    <%= form_for @pet, url:user_pets_path(@user.id) do |f| %>
      <p>
        <%= f.label :name%>
        <%= f.text_field :name, required: true %>
      </p>
      <div> 
          <p><b> Upload A Profile Picture For Your Pet</b></p>   
            <input
              type="hidden"
              role="uploadcare-uploader"
              data-images-only="true"
              data-crop=""
              name="pet[photo]"
            />  
        </div>
        <br>
      <p>
        <%= f.label :pet_type, required: true%>
        <%= f.select(:pet_type, [["Cat", "Cat"],["Dog", "Dog"],["Horse", "Horse"],
        ["Small Mammal", "Small Mammal"], ["Reptile/Amphibian", "Reptile/Amphibian"], ["Bird", "Bird"], ["Fish/Aquatic", "Fish/Aquatic"], ["Other", "Other"]]) %>
      </p>  
      
      <p>
        <%= f.label :breed%>
        <%= f.text_field :breed %>
      </p>
      <p>
        <%= f.label :birthday%>
        <%= f.date_field :birthday %>
      </p>
      <p>
        <%= f.radio_button :gender, "female" %>
        <%= f.label :gender, "Female", :value => "female" %>
        <%= f.radio_button :gender, "male" %>
        <%= f.label :gender, "Male", :value => "male" %>
        <br>
        <%= f.radio_button :altered, "altered" %>
        <%= f.label :altered, "Altered", :value => "altered" %>
        <%= f.radio_button :altered, "unaltered" %>
        <%= f.label :altered, "Unaltered", :value => "unaltered" %>
      </p>
      <p>
        <%= f.label :weight%>
        <%= f.text_field :weight %>
      </p>
      <p>
        <%= f.label :color%>
        <%= f.text_field :color %>
      </p>
      <br>
      <p>
        <%= f.label :microchip_company%> 
        <%= f.text_field :microchip_company %>
      <br>
        <%= f.label :microchip_company_website%>
        <%= f.url_field :microchip_company_website %>
      <br>
        <%= f.label :microchip_company_phone%>
        <%= f.telephone_field :microchip_company_phone %>
      <br>
        <%= f.label :microchip_registration_number%>
        <%= f.text_field :microchip_registration_number %>
      </p>
      <br>
      <p>
        <%= f.label :county_registration_number%>
        <%= f.text_field :county_registration_number %>
      <br>
        <%= f.label :county_registration_contact%>
        <%= f.text_field :county_registration_contact %>
      <br>
        <%= f.label :county_registration_expiration%>
        <%= f.date_field :county_registration_expiration %>
      </p>
      <br>
      <p>
        <%= f.label :rabies_vaccination_number%>
        <%= f.text_field :rabies_vaccination_number %>
      <br>
        <%= f.label :rabies_expiration%>
        <%= f.text_field :rabies_expiration %>
      </p>
      <p>
        <%= f.label :care_instructions%> <br>
        <%= f.text_area :care_instructions, rows: 10, cols: 80 %>
      </p>
      <p>
        <%= f.label :special_needs%> <br>
        <%= f.text_area :special_needs, rows: 10, cols: 80 %>
      </p> 
      <p>
        <%= f.label :historical_information%> <br>
        <%= f.text_area :historical_information, rows: 15, cols: 80 %>
      </p>  
      <!-- <div> nice to have functionality
        <p><b> Upload Pictures Of Your Pet</b></p>   
         <input
          type="hidden"
          role="uploadcare-uploader"
          data-images-only="true"
          data-multiple="true"
          data-crop=""
          name="pet[photos]"
          /> 
      </div> -->
      <div> 
        <p><b> Upload Records For Your Pet</b></p>   
        <input
          type="hidden"
          role="uploadcare-uploader"
          data-images-only="false"
          data-multiple="true"
          data-crop=""
          name="pet[vet_records]"
          value=""
          data-multiple-max="15"
        />  
      </div>
      <br>  
      <%= f.submit "save" %>
    <% end %>
  </div>

app/views/pets/show.html.erb
<h1 class = "showProfileName"><%= @pet.name %>'s Profile</h1>
<div class="center">
  <div class="profile_photo center" style="background-image: url(<%= @pet.photo %>); margin: 0 auto;"></div>
  <h5>
    <h4><%= @pet.name %></h4>
    <br>Type: <%= @pet.pet_type %>
    <br>Breed: <%= @pet.breed %>  
    <br>Gender: <%= @pet.gender %> 
    <br>Altered: <%= @pet.altered %> 
    <br>Weight: <%= @pet.weight %> 
    <br>Color: <%= @pet.color %> 
    <br>
    <br>Mircochip Number: <%= @pet.microchip_number %>
    <br>Mircochip Company: <%= @pet.microchip_company %>
    <br>Mircochip Company Website: <%= @pet.microchip_company_website %>
    <br>Mircochip Company Phone: <%= @pet.microchip_company_phone %>
    <br>
    <br>County Registration Number:<%= @pet.county_registration_number %>
    <br>County Registration Contact:<%= @pet.county_registration_contact %>
    <br>County Registration Expiration:<%= @pet.county_registration_expiration %>
    <br>
    <br>Rabies Vaccination Number:<%= @pet.rabies_vaccination_number %>
    <br>Rabies Expiration:<%= @pet.rabies_expiration %>
    <br>
    <br>Pet Care Instructions:<br><%= @pet.care_instructions %>
    <br>
    <br>Pet Special Needs:<br><%= @pet.special_needs %>
    <br>
    <br>Pet Historical Information:<br><%= @pet.historical_information %>
    <br>
</h5>

<% if @pet.vet_records.present? == true %>
  <h5>Records:</h5>
  <% @pet.vet_records.split("~")[1].split("/")[0].to_i.times do |i| %>
    <a class="record_picture" href="<%= "#{@pet.vet_records}nth/#{i}/" %>" alt=""> <i class="icon-file"></i> Record <%= i+1 %>   </a>
  <% end %>
<% end %>

<br><br>
<h4>
  <%= link_to "Edit", edit_user_pet_path %>  |  <%= link_to "Delete", user_pet_path, method: "delete", data: { confirm: "Are you sure you want to delete your pet's profile?\nThis can not be undone." } %> <br>
</h4>
 <br>

app/views/users/edit.html.erb
<h1>Edit <%= @user.first_name %>'s Profile</h1>
<div class="center">
  <%= form_for @user do |f| %>
    <div class="profile_photo center" style="background-image: url(<%= @user.photo %>); margin: 0 auto;"></div> 
    <br>
    <input type="hidden" role="uploadcare-uploader" data-multiple="false" name="user[photo]" value="<%= @user.photo %>"/>
  <br><br>
    <p>
      <%= f.label :first_name%>
      <%= f.text_field :first_name, required: true %>
    </p>
    <p>
      <%= f.label :last_name%>
      <%= f.text_field :last_name, required: true %>
    </p>
    <p>
      <%= f.label :address%>
      <%= f.text_field :address %>
    </p>
    <p>
      <%= f.label :vet_name%>
      <%= f.text_field :vet_name %>
    </p>
    <p>
      <%= f.label :vet_number%>
      <%= f.text_field :vet_number %>
    </p>
    <p>
      <%= f.label :vet_address%>
      <%= f.text_field :vet_address %>
    </p>
    <p>
      <%= f.label :email%>
      <%= f.email_field :email, required: true, autofocus: true %>
    </p>
    <p>
      <%= f.label :password%>
      <%= f.password_field :password %>
    </p>
    <%= f.submit %>

    
<% end %>

app/views/users/new.html.erb
<!-- <h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p> -->

<h1>Create a New User</h1>
<div class="center">
  <%= form_for @user do |f| %>
    <div> 
      <p><b> Upload Your Profile Picture</b></p>   
      <input
        type="hidden"
        role="uploadcare-uploader"
        data-images-only="true"
        data-crop=""
        name="user[photo]"
      />  
    </div>
    <br>
    <p>
      <%= f.label :first_name%>
      <%= f.text_field :first_name, required: true %>
    </p>
    <p>
      <%= f.label :last_name%>
      <%= f.text_field :last_name, required: true %>
    </p>
    <p>
      <%= f.label :address%>
      <%= f.text_field :address %>
    </p>
    <p>
      <%= f.label :vet_name%>
      <%= f.text_field :vet_name %>
    </p>
    <p>
      <%= f.label :vet_number%>
      <%= f.text_field :vet_number %>
    </p>
    <p>
      <%= f.label :vet_address%>
      <%= f.text_field :vet_address %>
    </p>
    <p>
      <%= f.label :email%>
      <%= f.email_field :email, required: true, autofocus: true %>
    </p>
    <p>
      <%= f.label :password%>
      <%= f.password_field :password %>
    </p>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/users/show.html.erb
<h1><%= @user.first_name %>'s Profile</h1>
<!-- user info -->
  <div class="center">
    <div class="inline" style="vertical-align: middle;">
      <% if @user.photo.present? == true %>
        <div class="profile_photo" style="background-image: url(<%= @user.photo %>); float: left"></div>
      <% end %> 
    </div> 
    <div class="inline" style="vertical-align: middle;">
      <h3><%= @user.first_name %> <%= @user.last_name %></h3> 
       
      <% if @user.vet_name.present? == true %>
        Vet info:  
        <br><%= @user.vet_name %>
        <br><%= @user.vet_number %>
        <br><%= @user.vet_address %>
      <% end %>
    </div>
  </div> 
<br>
<br>
<!-- pet info -->
  <h2><%= @user.first_name %>'s Pets</h2>
  <div class="center">
    <% @pets.each do |pet| %>
      <div class="inline center">
        <a href="/users/<%= @user.id %>/pets/<%= pet.id %>"><h4><%= pet.name %></h4></a>
        <div class="profile_photo center" style="background-image: url(<%= pet.photo %>) "></div>
      </div>  
    <% end %>
  </div> 

<br><br>

<!-- links -->
  <div class="center"> 
  <h4><%= link_to "Add Pet", new_user_pet_path(@user.id) %>  |  <%= link_to "Edit Profile", edit_user_path %>  |  <%= link_to "Delete Profile", user_path, method: "delete", data: { confirm: "Are you sure you want to delete your account?\nThis can not be undone." } %> </h4>
  </div>
  